### PR TITLE
Compilation fixes on OSX

### PR DESCRIPTION
**Pull request by willpett**
I had to change a few things to get scompress to compile on my mac. I also tidied up some typos along the way, so it looks like more changes than it really is.

### CODE REVIEW

**Comment by willpett** [comment]
Thanks for the great tool! With it I successfully extracted all the sprites from alttp and converted them to bmp.

**Comment by Skarsnik** [comment]
hm, Os X does not have a size_t type? that really weird, maybe it just need another include.

**Comment by willpett** [comment]
it does have size_t, but clang gives a warning about casting it to unsigned int, and since -Werror is set, it throws an error.

**Comment by Skarsnik** [comment]
Hm, I should check all my size_t stuff, it's the proper type to use when addressing pointer :)

**Pull request merged**
